# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/JyothiSriLakshmi-1305/FlyRank-ML-Internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [18]:
files = api.list_repo_files(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset"
)

for name in files[:60]:
    print(name)

.gitattributes
README.md
dim_clients.parquet
dim_content.parquet
fact_content_daily_performance/month=2025-01/data_0.parquet
fact_content_daily_performance/month=2025-02/data_0.parquet
fact_content_daily_performance/month=2025-03/data_0.parquet
fact_content_daily_performance/month=2025-04/data_0.parquet
fact_content_daily_performance/month=2025-05/data_0.parquet
fact_content_daily_performance/month=2025-06/data_0.parquet
fact_content_daily_performance/month=2025-07/data_0.parquet
fact_content_daily_performance/month=2025-08/data_0.parquet
fact_content_daily_performance/month=2025-09/data_0.parquet
fact_content_daily_performance/month=2025-10/data_0.parquet
fact_content_daily_performance/month=2025-11/data_0.parquet
fact_content_daily_performance/month=2025-12/data_0.parquet
fact_content_daily_performance/month=2026-01/data_0.parquet
fact_content_daily_performance/month=2026-02/data_0.parquet
fact_content_daily_performance/month=2026-03/data_0.parquet
fact_content_daily_performance/month=2026-04/data_0.parquet
fact_content_daily_performance/month=2026-05/data_0.parquet
fact_content_daily_performance/month=2026-06/data_0.parquet
fact_content_daily_performance_sample.parquet
fact_content_query_90d.parquet

In [19]:
import pandas as pd
import pyarrow.parquet as pq
from huggingface_hub import hf_hub_download

file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance/month=2026-03/data_0.parquet",
    repo_type="dataset",
    token=token
)

parquet_file = pq.ParquetFile(file_path)

print("Columns:")
print(parquet_file.schema.names)

print("\nRows in March file:", parquet_file.metadata.num_rows)

Columns:
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

Rows in March file: 9841378

In [20]:
sample_df = pd.read_parquet(file_path, engine="pyarrow").head(5)

print("First 5 rows:")
display(sample_df)

print("\nColumns:")
print(sample_df.columns.tolist())

First 5 rows:

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20,0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125,1,616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11,0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columns:
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [21]:
small_table = parquet_file.read_row_group(0).slice(0, 5)
sample_df = small_table.to_pandas()

display(sample_df)
print("Columns:", sample_df.columns.tolist())

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20,0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125,1,616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11,0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columns: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [ ]:
for i, column in enumerate(parquet_file.schema.names, start=1):
    print(f"{i}. {column}")

In [22]:
sample_df = parquet_file.read_row_group(0).to_pandas()

key_columns = ["report_date", "client_hash_id", "content_hash_id"]

print("Rows checked:", len(sample_df))
print("Duplicate keys:", sample_df.duplicated(subset=key_columns).sum())
print("Unique keys:", sample_df[key_columns].drop_duplicates().shape[0])

Rows checked: 104096
Duplicate keys: 0
Unique keys: 104096

In [23]:
import pyarrow.compute as pc

date_min = None
date_max = None

for batch in parquet_file.iter_batches(
    columns=["report_date"],
    batch_size=200_000
):
    dates = batch.column("report_date")
    batch_min = pc.min(dates).as_py()
    batch_max = pc.max(dates).as_py()

    if batch_min is not None:
        date_min = batch_min if date_min is None else min(date_min, batch_min)
        date_max = batch_max if date_max is None else max(date_max, batch_max)

print("March file rows:", parquet_file.metadata.num_rows)
print("Minimum report date:", date_min)
print("Maximum report date:", date_max)

March file rows: 9841378
Minimum report date: 2026-03-01
Maximum report date: 2026-03-31

In [24]:
availability_counts = {"gsc_true": 0, "ga4_true": 0, "both_true": 0}

for batch in parquet_file.iter_batches(
    columns=["gsc_data_available", "ga4_data_available"],
    batch_size=200_000
):
    gsc = batch.column("gsc_data_available")
    ga4 = batch.column("ga4_data_available")

    gsc_true = pc.equal(gsc, True)
    ga4_true = pc.equal(ga4, True)

    availability_counts["gsc_true"] += pc.sum(
        pc.fill_null(gsc_true, False)
    ).as_py()

    availability_counts["ga4_true"] += pc.sum(
        pc.fill_null(ga4_true, False)
    ).as_py()

    availability_counts["both_true"] += pc.sum(
        pc.fill_null(pc.and_(gsc_true, ga4_true), False)
    ).as_py()

print("GSC available:", availability_counts["gsc_true"])
print("GA4 available:", availability_counts["ga4_true"])
print("Both available:", availability_counts["both_true"])

GSC available: 3611061
GA4 available: 413966
Both available: 364347

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

**Research lane:** Content opportunity scoring — ranking content pages by review priority.

**Unit of analysis:** One row represents one content page for a particular reporting period. I will verify the actual row grain against the dataset before finalizing this statement.

**Development time window:** March 2026 (`month=2026-03`). I will use this month for development and avoid using the June 2026 `_sample` tables to make modeling decisions.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

### Field contract

**Features (candidate inputs):**
- `gsc_impressions` — search visibility.
- `gsc_clicks` — search clicks.
- `gsc_avg_position` — average search position.
- `ga4_pageviews` — page views from analytics.
- `content_age_days` — content age, if confirmed in the content dimension table.

Each feature must be available at the decision moment. I will verify column availability and missingness before using it.

**Label / proxy:**
- `trend_direction` is a candidate proxy from the content dimension, if available.
- A downward trend may indicate a page worth reviewing, but it does not prove that updating the page will improve performance.

**Context:**
- `report_date`, `client_hash_id`, and `content_hash_id` identify the reporting date, client, and content page.
- `gsc_data_available` and `ga4_data_available` indicate whether the respective data sources are available.

**Deliberately excluded:**
- `gsc_clicks` or other same-period outcome measurements must not be used as predictors if they would not be known at the decision moment. I will exclude any label-derived field from the feature set to prevent leakage.

In [25]:
content_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="dim_content.parquet",
    repo_type="dataset",
    token=token
)

content_file = pq.ParquetFile(content_path)

print("dim_content columns:")
for column in content_file.schema.names:
    print(column)

print("\nRows in dim_content:", content_file.metadata.num_rows)

dim_content columns:
client_hash_id
content_hash_id
keyword_hash_id
url_hash_id
keyword_char_count
keyword_token_count
url_char_count
content_created_date
content_updated_date
content_type
search_volume
competition
competition_level
cpc
main_intent
backlinks
category_count
keyword_created_date
provider_used
model_used
char_count
word_count
last_optimized_date
optimization_eligible_date
is_published
is_deleted

Rows in dim_content: 519606

In [26]:
print("First 20 dim_content columns:")
print(content_file.schema.names[:20])

First 20 dim_content columns:
['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used']

In [28]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [27]:
# Query 1: Verify candidate row grain in the first row group.
key_columns = ["report_date", "client_hash_id", "content_hash_id"]

print("Rows checked:", len(sample_df))
print(
    "Duplicate keys:",
    sample_df.duplicated(subset=key_columns).sum()
)
print(
    "Unique keys:",
    sample_df[key_columns].drop_duplicates().shape[0]
)

Rows checked: 104096
Duplicate keys: 0
Unique keys: 104096

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

### Data limitations

1. **Incomplete availability:** Not every row has GSC or GA4 data available, so missing data must not automatically be treated as zero.
2. **Class imbalance:** The target proxy may be unevenly distributed, so accuracy alone would be misleading.
3. **Proxy limitation:** A downward trend does not prove that a content page needs updating or that updating it will improve performance.
4. **Data leakage:** Features must be available at the decision moment. Label-derived information must not enter the feature set.
5. **Validation limitation:** The duplicate-key check so far covers only the first row group. Full-month uniqueness still needs verification.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.